apiVersion: v1
kind: Service
metadata:
  name: hello-airwolfnh
  labels:
    app: hello-airwolfnh
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-airwolfnh
    tier: hello-airwolfnh
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-airwolfnh
  labels:
    app: hello-airwolfnh
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-airwolfnh
        tier: hello-airwolfnh
    spec:
      containers:
      - image: airwolfnh/hello-airwolfnh:__IMAGE__
        name: hello-airwolfnh
        ports:
        - containerPort: 80
          name: hello-airwolfnh
